### ISSUE TITLE
Webhook created, but secret not appearing

### ISSUE THREAD

**Issue by ExsyDev** [chatwoot/chatwoot#13862]
### Describe the bug

Hello. I have a issue, I creeated webhook for event: conversation_created, but webhook secret I don't see. Why?

### To Reproduce

Self Hosted, simple go in integrations and try to create webhook

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by Timur2915** [comment]
Looks like webhooks are not actually signed (at least in 4.11.1), and the current documentation is misleading...

**Comment by kostopravby** [comment]
Also, after upgrading from 4.11.1 to 4.12.0, I don't see my webhooks, but they are working. Attempts to recreate them cause an error that this URL is already in use.

**Comment by kostopravby** [comment]
Chatwoot v4.12.0. When attempting to create a new webhook, the following message is displayed: "could not connect to woot server. please try again later"

**Comment by ataranouski** [comment]
While opening webhook page:
`rails-1          | I, [2026-03-25T11:34:24.193885 #1]  INFO -- : [382f5798-f6b4-406d-b74e-5ebdfc724636] Completed 500 Internal Server Error in 49ms (ActiveRecord: 32.2ms | Allocations: 13876)

rails-1          | F, [2026-03-25T11:34:24.206149 #1] FATAL -- : [382f5798-f6b4-406d-b74e-5ebdfc724636]
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] ActionView::Template::Error (undefined method 'secret' for an instance of Webhook):
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     3: json.url webhook.url
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     4: json.account_id webhook.account_id
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     5: json.subscriptions webhook.subscriptions
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     6: json.secret webhook.secret
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     7: if webhook.inbox
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     8:   json.inbox do
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]     9:     json.id webhook.inbox.id
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636]
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/views/api/v1/accounts/webhooks/_webhook.json.jbuilder:6:in '_app_views_api_v__accounts_webhooks__webhook_json_jbuilder__3250401576204305956_105184'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/views/api/v1/accounts/webhooks/index.json.jbuilder:3:in 'block (2 levels) in _app_views_api_v__accounts_webhooks_index_json_jbuilder__4455425086445190284_105160'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/views/api/v1/accounts/webhooks/index.json.jbuilder:2:in 'block in _app_views_api_v__accounts_webhooks_index_json_jbuilder__4455425086445190284_105160'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/views/api/v1/accounts/webhooks/index.json.jbuilder:1:in '_app_views_api_v__accounts_webhooks_index_json_jbuilder__4455425086445190284_105160'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/controllers/concerns/switch_locale.rb:56:in 'SwitchLocale#set_locale'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/controllers/concerns/switch_locale.rb:29:in 'SwitchLocale#switch_locale_using_account_locale'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/controllers/concerns/request_exception_handler.rb:11:in 'RequestExceptionHandler#handle_with_exception'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/controllers/concerns/switch_locale.rb:56:in 'SwitchLocale#set_locale'
rails-1          | [382f5798-f6b4-406d-b74e-5ebdfc724636] app/controllers/concerns/switch_locale.rb:19:in 'SwitchLocale#switch_locale'`

**Comment by edumoritz** [comment]
We ran into this kind of issue a few times with webhook integrations and it is surprisingly easy for it to turn into a trust problem for users.

If the secret exists but is not visible, people are left guessing whether the webhook is actually configured correctly or not. Even a small mismatch there makes retries and debugging much harder.

One thing that helped us was treating webhook config visibility and delivery validation as separate concerns:

* make it obvious whether the secret was generated successfully
* make it obvious whether the endpoint is actually receiving signed requests
* keep a small delivery/debug surface so users do not have to guess where it failed

We ended up building some internal monitoring around this exact kind of integration drift because the painful part usually is not the initial setup, it is discovering later that the config looked fine but behavior was off.

Curious if the issue here is only UI visibility or if the secret is also missing in the actual webhook signing flow.

**Comment by pranavrajs** [comment]
Hello everyone, This is not a bug with the product, the migrations were not completed which is why you are seeing this error. 

```
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] ActionView::Template::Error (undefined method 'secret' for an instance of Webhook):
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 3: json.url webhook.url
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 4: json.account_id webhook.account_id
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 5: json.subscriptions webhook.subscriptions
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 6: json.secret webhook.secret
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 7: if webhook.inbox
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 8: json.inbox do
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 9: json.id webhook.inbox.id
rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636]
```

This is the problem. Please run db migrations after you upgrade and this should work. Please feel free to reopen the issue if it still doesn't fix the problem.

@edumoritz I'm not sure the feedback you shared is related. Please feel free to create a new ticket if it is not.

**Comment by Timur2915** [comment]
> Hello everyone, This is not a bug with the product, the migrations were not completed which is why you are seeing this error.
> 
> ```
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] ActionView::Template::Error (undefined method 'secret' for an instance of Webhook):
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 3: json.url webhook.url
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 4: json.account_id webhook.account_id
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 5: json.subscriptions webhook.subscriptions
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 6: json.secret webhook.secret
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 7: if webhook.inbox
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 8: json.inbox do
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636] 9: json.id webhook.inbox.id
> rails-1 | [382f5798-f6b4-406d-b74e-5ebdfc724636]
> ```
> 
> This is the problem. Please run db migrations after you upgrade and this should work. Please feel free to reopen the issue if it still doesn't fix the problem.
> 
> [@edumoritz](https://github.com/edumoritz) I'm not sure the feedback you shared is related. Please feel free to create a new ticket if it is not.

This was reproduced on a clean installation with all migrations applied successfully.

The database schema does not contain any secret (or similar) field, while webhooks are created normally. However, no secret is returned after creation and no signature is present in webhook requests.

So this is still an actual issue and is not resolved by running migrations.

**Comment by pranavrajs** [comment]
@scmmishra Please check if you can reproduce it

**Comment by rnagulapalle** [comment]
went little deeper in current source and i think thread is mixing old runtime problem with current docs/spec state

on current develop, account webhooks do have real secret support end to end:

webhooks.secret exists in schema
Webhook includes WebhookSecretable
API webhook create/index views serialize webhook.secret
listener passes webhook.secret into WebhookJob
Webhooks::Trigger adds both X-Chatwoot-Timestamp and X-Chatwoot-Signature
so on current source this does not look like “secret/signing feature is missing” anymore

but i did notice one real mismatch still: the OpenAPI / swagger schema for webhook does not include secret, even though API view returns it. so there is still contract drift there.

feels like issue now needs version split more clearly:

older self-hosted / upgrade path where secret field was not available or migrations were not in effect
current source where feature exists, but API spec/docs are behind actual response shape
if this issue is meant for current code, then i think better repro is:

exact image / version
whether webhooks.secret column exists
response body from POST /api/v1/accounts/:id/webhooks
whether outbound request contains X-Chatwoot-Timestamp and X-Chatwoot-Signature
otherwise discussion keeps mixing old install state with current implementation

**Comment by sojan-official** [comment]
Thanks for the report and the follow-up details. I re-checked this against current `develop`.

On current source, webhook secrets/signing are present end to end:
- `webhooks.secret` exists in the schema.
- Account webhooks generate a per-webhook `secret`.
- The account webhook API serializes `secret` in the response.
- Outbound account webhook deliveries pass that secret into the webhook job.
- Signed webhook requests include `X-Chatwoot-Timestamp` and `X-Chatwoot-Signature`.
- Deliveries include `X-Chatwoot-Delivery` when a delivery id is available.

Version-wise, this was not present in `v4.11.1`. The account webhook secret/signing support appears in `v4.11.2` via #13573 (`feat: add per-webhook secret with backfill migration`). API channel / agent bot webhook signing support was expanded later in `v4.13.0` via #13892.

So for current `develop`, I don't see the original product issue anymore. The remaining gap was OpenAPI/schema drift: the webhook schema did not document the returned `secret`, the signing headers, or the typing webhook events that are already supported by the app. I updated #14199 to cover that contract/documentation gap and regenerate the swagger outputs.

For older self-hosted installs, please upgrade to at least `v4.11.2` for account webhook secrets/signing and make sure database migrations have run so the `webhooks.secret` column exists.
