### ISSUE TITLE
pg gem fails to compile with Ruby 3.4.4 due to incorrect declaration in extconf.rb

### ISSUE THREAD

**Issue by maxihoster** [chatwoot/chatwoot#11782]
### Describe the bug

After updating Chatwoot to the latest version and using Ruby 3.4.4, the pg gem (v1.5.3) fails to compile during bundle install.

The error stems from a type conflict in the extconf.rb check:

vbnet
Copier
Modifier
error: conflicting types for ‘PQconnectdb’; have ‘void()’
note: previous declaration of ‘PQconnectdb’ with type ‘PGconn *(const char *)’
This occurs because extconf.rb declares:

c
Copier
Modifier
extern void PQconnectdb();
Which conflicts with the correct signature from libpq-fe.h:

c
Copier
Modifier
extern PGconn *PQconnectdb(const char *conninfo);
As a result, the gem fails to build even though libpq-dev and pg_config are correctly installed and detected.

Workaround: Downgrading to Ruby 3.2.x resolves the issue immediately, as the pg gem compiles fine under that version.

Suggestion: Either update Chatwoot’s Ruby compatibility guidelines or report this upstream to the pg gem maintainers so the detection logic can be updated for Ruby 3.4+.

### To Reproduce

cwctl --upgrade
After this 502 bad gateway!

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
Please use the latest develop branch. We cannot reproduce the issue on our end.
