### ISSUE TITLE
Error adding labels to old dialogues after updating to 3.4.0

### ISSUE THREAD

**Issue by JackFrost** [chatwoot/chatwoot#8683]
### Describe the bug

After updating from version 3.3.1 to 3.4.0, when adding a label to an old dialogue, an error occurs: { “status”: 500, “error”: “Internal Server Error” }
Labels are added to new dialogues without errors.

The request is sent to the following path, where the error occurs:
/api/v1/accounts/2/conversations/85770/labels

Chatwoot is running through Docker on its server

from docker container logs:
```
I, [2024-01-10T10:05:52.110520 #1]  INFO -- : source=rack-timeout id=dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853 timeout=15000ms state=ready
I, [2024-01-10T10:05:52.111873 #1]  INFO -- : [dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] Started POST "/api/v1/accounts/2/conversations/85770/labels" for 123.123.123.123 at 2024-01-10 10:05:52 +0000
I, [2024-01-10T10:05:52.113700 #1]  INFO -- : [dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] Processing by Api::V1::Accounts::Conversations::LabelsController#create as JSON
I, [2024-01-10T10:05:52.115161 #1]  INFO -- : [dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853]   Parameters: {"labels"=>["test"], "account_id"=>"2", "conversation_id"=>"85770", "label"=>{}}
I, [2024-01-10T10:05:52.127986 #1]  INFO -- : [dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] Completed 500 Internal Server Error in 13ms (ActiveRecord: 5.1ms | Allocations: 4951)
F, [2024-01-10T10:05:52.128911 #1] FATAL -- : [dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853]   
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] NoMethodError (undefined method `caching_tag_list_on?' for Conversation:Class):
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853]   
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/models/concerns/labelable.rb:9:in `update_labels'
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/controllers/concerns/label_concern.rb:3:in `create'
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
I, [2024-01-10T10:05:52.129123 #1]  INFO -- : source=rack-timeout id=dad7a8ac-3bca-4cea-a7ce-f9c46c0ae853 timeout=15000ms service=19ms state=completed
```

### To Reproduce

ups

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Docker (if applicable)

Docker version
`
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       5d6db84
  Built:            Thu May 18 08:38:34 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:
`

`
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.2
OpenSSL version: OpenSSL 3.0.11 19 Sep 2023
`

**Comment by pranavrajs** [comment]
@JackFrost The error shows that `caching_tag_list_on?` is missing. Either the db migrations have not been complete or you have not restarted the services. Please do these, it would be fixed.
