### PR TITLE
Fix NoMethodError on conversation creation when assignee_agent_bot_id migration is incomplete

### LINKED ISSUE #12934: 500 error when creating conversation via API after update to 4.8.0
### Describe the bug

I have a workflow where my CRM creates a new contact in Chatwoot and then creates a new conversation (API::channel) for this contact.
After updating to v4.8.0, the conversation creation endpoint started failing with the following error:

```
I, [2025-11-24T08:43:41.444197 #1]  INFO -- : [444fc09f-879d-4195-bb38-8b8afb90ff62]   Parameters: {"contact_id" => 19204, "inbox_id" => 29, "message" => {"content" => "ertywertywert"}, "assignee_id" => "1", "account_id" => "3", "conversation" => {"inbox_id" => 29, "assignee_id" => "1", "contact_id" => 19204}}
I, [2025-11-24T08:43:41.471661 #1]  INFO -- : [444fc09f-879d-4195-bb38-8b8afb90ff62] Completed 500 Internal Server Error in 27ms (ActiveRecord: 7.7ms | Allocations: 3414)
F, [2025-11-24T08:43:41.474721 #1] FATAL -- : [444fc09f-879d-4195-bb38-8b8afb90ff62]
[444fc09f-879d-4195-bb38-8b8afb90ff62] NoMethodError (undefined method 'assignee_agent_bot_id=' for an instance of Conversation):
[444fc09f-879d-4195-bb38-8b8afb90ff62]
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/models/conversation.rb:247:in 'Conversation#reset_agent_bot_when_assignee_present'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/builders/conversation_builder.rb:17:in 'ConversationBuilder#create_new_conversation'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/builders/conversation_builder.rb:5:in 'ConversationBuilder#perform'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/controllers/api/v1/accounts/conversations_controller.rb:41:in 'block in Api::V1::Accounts::ConversationsController#create'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/controllers/api/v1/accounts/conversations_controller.rb:40:in 'Api::V1::Accounts::ConversationsController#create'
```

### To Reproduce

1. Update Chatwoot from 4.7.0 to 4.8.0.
2. Run the database migration: docker compose run --rm rails bundle exec rails db:chatwoot_prepare
3. Create an inbox of type Channel::Api.
4. Send a payload to create a conversation, for example:
`{
  "contact_id": 19204,
  "inbox_id": 29,
  "message": { "content": "ertywertywert" },
  "assignee_id": "1",
  "account_id": "3",
  "conversation": {
    "inbox_id": 29,
    "assignee_id": "1",
    "contact_id": 19204
  }
}`

### Expected behavior

_No response_

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

_No response_

### Browser and version

_No response_

### Docker (if applicable)

**docker version**
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.24
  GitCommit:        88bf19b2105c8b17560993bee28a01ddc2f97182
 runc:
  Version:          1.2.2
  GitCommit:        v1.2.2-0-g7cb3632
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**docker info**
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 28
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-48-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.25GiB
 Name: chatwoot-ubuntu
 ID: 535c1608-c009-41e5-8fe9-ed9f35eed64b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Docker Compose version v2.29.7

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LindokuhleYende**
<html>
<body>
<p data-line="3" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Closes #12934</p><h2 data-line="5" class="code-line" dir="auto" id="problem" style="margin-top: 24px; font-weight: 600; margin-bottom: 16px; line-height: 1.25; font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid rgba(255, 255, 255, 0.18); border-top-color: rgba(255, 255, 255, 0.18); border-right-color: rgba(255, 255, 255, 0.18); border-left-color: rgba(255, 255, 255, 0.18); position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Problem</h2><p data-line="7" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">After upgrading to v4.8.0, creating a conversation via the API with an<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">assignee_id</code><span> </span>crashes with HTTP 500:</p><pre style="margin-top: 0px; background-color: rgba(10, 10, 10, 0.4); border-color: rgb(214, 222, 235); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; padding: 16px; border-radius: 3px; overflow: auto; white-space: pre-wrap; color: rgb(214, 222, 235); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code data-line="10" class="code-line" dir="auto" style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(214, 222, 235); background: none; padding: 0px; border-radius: 4px; font-size: 1em; line-height: 1.357em; display: inline-block; tab-size: 4; position: relative;">NoMethodError (undefined method 'assignee_agent_bot_id=' for an instance of Conversation):
  app/models/conversation.rb:247:in 'Conversation#reset_agent_bot_when_assignee_present'
  app/builders/conversation_builder.rb:17:in 'ConversationBuilder#create_new_conversation'
</code></pre><h2 data-line="16" class="code-line" dir="auto" id="root-cause" style="margin-top: 24px; font-weight: 600; margin-bottom: 16px; line-height: 1.25; font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid rgba(255, 255, 255, 0.18); border-top-color: rgba(255, 255, 255, 0.18); border-right-color: rgba(255, 255, 255, 0.18); border-left-color: rgba(255, 255, 255, 0.18); position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Root Cause</h2><p data-line="18" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">PR #12836 added the<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">assignee_agent_bot_id</code><span> </span>column to the<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">conversations</code><span> </span>table and introduced a<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">before_create</code><span> </span>callback (<code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">reset_agent_bot_when_assignee_present</code>) that clears this column when a human assignee is present.</p><p data-line="22" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">On some self-hosted installations (particularly those running Postgres &lt; 15 or without the<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">pgvector</code><span> </span>extension),<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">db:chatwoot_prepare</code><span> </span>exits before reaching the<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">AddAssigneeAgentBotIdToConversations</code><span> </span>migration. This leaves the database without the column while the model code assumes it exists.</p><p data-line="27" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ActiveRecord generates attribute accessors at boot time from the actual DB schema. Because the column is absent, the<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">assignee_agent_bot_id=</code><span> </span>setter is never defined, and calling it in the callback raises<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">NoMethodError</code>.</p><h2 data-line="31" class="code-line" dir="auto" id="solution" style="margin-top: 24px; font-weight: 600; margin-bottom: 16px; line-height: 1.25; font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid rgba(255, 255, 255, 0.18); border-top-color: rgba(255, 255, 255, 0.18); border-right-color: rgba(255, 255, 255, 0.18); border-left-color: rgba(255, 255, 255, 0.18); position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Solution</h2><p data-line="33" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Guard the assignment in<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">reset_agent_bot_when_assignee_present</code><span> </span>with a<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">column_names</code><span> </span>check:</p><pre style="margin-top: 0px; background-color: rgba(10, 10, 10, 0.4); border-color: rgb(214, 222, 235); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; padding: 16px; border-radius: 3px; overflow: auto; white-space: pre-wrap; color: rgb(214, 222, 235); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code data-line="36" class="code-line language-ruby" dir="auto" style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(214, 222, 235); background: none; padding: 0px; border-radius: 4px; font-size: 1em; line-height: 1.357em; display: inline-block; tab-size: 4; position: relative;"><span class="hljs-comment" style="color: rgb(87, 166, 74); font-style: italic;"># Before</span>
<span class="hljs-keyword" style="color: rgb(86, 156, 214);">def</span> <span class="hljs-title function_" style="color: rgb(220, 220, 220);">reset_agent_bot_when_assignee_present</span>
  <span class="hljs-keyword" style="color: rgb(86, 156, 214);">return</span> <span class="hljs-keyword" style="color: rgb(86, 156, 214);">unless</span> assignee_id.present?

  <span class="hljs-variable language_" style="color: rgb(189, 99, 197);">self</span>.assignee_agent_bot_id = <span class="hljs-literal" style="color: rgb(86, 156, 214);">nil</span>
<span class="hljs-keyword" style="color: rgb(86, 156, 214);">end</span>

<span class="hljs-comment" style="color: rgb(87, 166, 74); font-style: italic;"># After</span>
<span class="hljs-keyword" style="color: rgb(86, 156, 214);">def</span> <span class="hljs-title function_" style="color: rgb(220, 220, 220);">reset_agent_bot_when_assignee_present</span>
  <span class="hljs-keyword" style="color: rgb(86, 156, 214);">return</span> <span class="hljs-keyword" style="color: rgb(86, 156, 214);">unless</span> assignee_id.present?
  <span class="hljs-keyword" style="color: rgb(86, 156, 214);">return</span> <span class="hljs-keyword" style="color: rgb(86, 156, 214);">unless</span> <span class="hljs-variable language_" style="color: rgb(189, 99, 197);">self</span>.<span class="hljs-keyword" style="color: rgb(86, 156, 214);">class</span>.column_names.<span class="hljs-keyword" style="color: rgb(86, 156, 214);">include</span>?(<span class="hljs-string" style="color: rgb(214, 157, 133);">'assignee_agent_bot_id'</span>)

  <span class="hljs-variable language_" style="color: rgb(189, 99, 197);">self</span>.assignee_agent_bot_id = <span class="hljs-literal" style="color: rgb(86, 156, 214);">nil</span>
<span class="hljs-keyword" style="color: rgb(86, 156, 214);">end</span>
</code></pre><p data-line="53" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">column_names</code><span> </span>is cached by ActiveRecord after the first call, so there is no per-request database round-trip. This is the same pattern used in the Captain AI initializer for<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">installation_configs</code>.</p><h2 data-line="57" class="code-line" dir="auto" id="alternatives-considered" style="margin-top: 24px; font-weight: 600; margin-bottom: 16px; line-height: 1.25; font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid rgba(255, 255, 255, 0.18); border-top-color: rgba(255, 255, 255, 0.18); border-right-color: rgba(255, 255, 255, 0.18); border-left-color: rgba(255, 255, 255, 0.18); position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Alternatives Considered</h2>
Approach | Reason not chosen
-- | --
respond_to?(:assignee_agent_bot_id=) | Less explicit; would mask method-rename bugs on fully migrated installs
Remove the callback entirely | Loses the intended bot-reset behaviour on fully migrated installs
Rescue NoMethodError | Catching NoMethodError broadly is an anti-pattern in Rails models

<h2 data-line="65" class="code-line" dir="auto" id="testing" style="margin-top: 24px; font-weight: 600; margin-bottom: 16px; line-height: 1.25; font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid rgba(255, 255, 255, 0.18); border-top-color: rgba(255, 255, 255, 0.18); border-right-color: rgba(255, 255, 255, 0.18); border-left-color: rgba(255, 255, 255, 0.18); position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Testing</h2><ul data-line="67" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 0.7em; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li data-line="67" class="code-line" dir="auto" style="position: relative;">Added unit specs for<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">reset_agent_bot_when_assignee_present</code><span> </span>covering:<ul data-line="68" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 0.7em; position: relative;"><li data-line="68" class="code-line" dir="auto" style="position: relative;">Column present → clears<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">assignee_agent_bot_id</code><span> </span>on create</li><li data-line="69" class="code-line" dir="auto" style="position: relative;">Column absent (simulated) → no<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">NoMethodError</code><span> </span>raised</li><li data-line="70" class="code-line" dir="auto" style="position: relative;">No assignee set → callback exits early cleanly</li></ul></li><li data-line="71" class="code-line" dir="auto" style="position: relative;">Added integration-level regression spec that mirrors the exact API payload from Issue #12934 through<span> </span><code style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 1px 3px; border-radius: 4px; font-size: 1em; line-height: 1.357em;">ConversationBuilder</code></li></ul><h2 data-line="74" class="code-line" dir="auto" id="how-to-reproduce-before-fix" style="margin-top: 24px; font-weight: 600; margin-bottom: 16px; line-height: 1.25; font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid rgba(255, 255, 255, 0.18); border-top-color: rgba(255, 255, 255, 0.18); border-right-color: rgba(255, 255, 255, 0.18); border-left-color: rgba(255, 255, 255, 0.18); position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">How to Reproduce (before fix)</h2><pre style="margin-top: 0px; background-color: rgba(10, 10, 10, 0.4); border-color: rgb(214, 222, 235); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; padding: 16px; border-radius: 3px; overflow: auto; white-space: pre-wrap; color: rgb(214, 222, 235); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code data-line="76" class="code-line language-ruby" dir="auto" style="font-family: Consolas, &quot;Courier New&quot;, monospace; color: rgb(214, 222, 235); background: none; padding: 0px; border-radius: 4px; font-size: 1em; line-height: 1.357em; display: inline-block; tab-size: 4; position: relative;"><span class="hljs-comment" style="color: rgb(87, 166, 74); font-style: italic;"># In rails console on an install where the migration did not run:</span>
account  = <span class="hljs-title class_" style="color: rgb(220, 220, 220);">Account</span>.first
inbox    = <span class="hljs-title class_" style="color: rgb(220, 220, 220);">Inbox</span>.where(<span class="hljs-symbol" style="color: rgb(86, 156, 214);">channel_type:</span> <span class="hljs-string" style="color: rgb(214, 157, 133);">'Channel::Api'</span>).first
contact  = <span class="hljs-title class_" style="color: rgb(220, 220, 220);">Contact</span>.first
agent    = <span class="hljs-title class_" style="color: rgb(220, 220, 220);">User</span>.first

<span class="hljs-title class_" style="color: rgb(220, 220, 220);">ConversationBuilder</span>.new(
  <span class="hljs-symbol" style="color: rgb(86, 156, 214);">params:</span> { <span class="hljs-symbol" style="color: rgb(86, 156, 214);">inbox_id:</span> inbox.id, <span class="hljs-symbol" style="color: rgb(86, 156, 214);">contact_id:</span> contact.id,
            <span class="hljs-symbol" style="color: rgb(86, 156, 214);">assignee_id:</span> agent.id, <span class="hljs-symbol" style="color: rgb(86, 156, 214);">message:</span> { <span class="hljs-symbol" style="color: rgb(86, 156, 214);">content:</span> <span class="hljs-string" style="color: rgb(214, 157, 133);">'test'</span> } },
  <span class="hljs-symbol" style="color: rgb(86, 156, 214);">account:</span> account
).perform
<span class="hljs-comment" style="color: rgb(87, 166, 74); font-style: italic;"># =&gt; raises NoMethodError: undefined method 'assignee_agent_bot_id='</span>
</code></pre><p data-line="91" class="code-line" dir="auto" style="margin-top: 0px; margin-bottom: 16px; position: relative; color: rgb(214, 222, 235); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">After this fix the call completes successfully</p>
</body>
</html>

### CODE REVIEW

**Comment by sojan-official** [comment]
Thanks for picking this up.

We don’t want to add support for schema drift between application code and database migrations. `pgvector` is mandatory for 4.x releases, and the recommended path is to keep the instance fully up to date with all migrations.

Adding guards like this can mask an incomplete or broken upgrade path and may leave the instance in an inconsistent state. I think we should avoid this change and instead guide users to fix the failed migration/setup issue.
