### ISSUE TITLE
500 error when creating conversation via API after update to 4.8.0

### ISSUE THREAD

**Issue by el-vis** [chatwoot/chatwoot#12934]
### Describe the bug

I have a workflow where my CRM creates a new contact in Chatwoot and then creates a new conversation (API::channel) for this contact.
After updating to v4.8.0, the conversation creation endpoint started failing with the following error:

```
I, [2025-11-24T08:43:41.444197 #1]  INFO -- : [444fc09f-879d-4195-bb38-8b8afb90ff62]   Parameters: {"contact_id" => 19204, "inbox_id" => 29, "message" => {"content" => "ertywertywert"}, "assignee_id" => "1", "account_id" => "3", "conversation" => {"inbox_id" => 29, "assignee_id" => "1", "contact_id" => 19204}}
I, [2025-11-24T08:43:41.471661 #1]  INFO -- : [444fc09f-879d-4195-bb38-8b8afb90ff62] Completed 500 Internal Server Error in 27ms (ActiveRecord: 7.7ms | Allocations: 3414)
F, [2025-11-24T08:43:41.474721 #1] FATAL -- : [444fc09f-879d-4195-bb38-8b8afb90ff62]
[444fc09f-879d-4195-bb38-8b8afb90ff62] NoMethodError (undefined method 'assignee_agent_bot_id=' for an instance of Conversation):
[444fc09f-879d-4195-bb38-8b8afb90ff62]
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/models/conversation.rb:247:in 'Conversation#reset_agent_bot_when_assignee_present'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/builders/conversation_builder.rb:17:in 'ConversationBuilder#create_new_conversation'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/builders/conversation_builder.rb:5:in 'ConversationBuilder#perform'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/controllers/api/v1/accounts/conversations_controller.rb:41:in 'block in Api::V1::Accounts::ConversationsController#create'
[444fc09f-879d-4195-bb38-8b8afb90ff62] app/controllers/api/v1/accounts/conversations_controller.rb:40:in 'Api::V1::Accounts::ConversationsController#create'
```

### To Reproduce

1. Update Chatwoot from 4.7.0 to 4.8.0.
2. Run the database migration: docker compose run --rm rails bundle exec rails db:chatwoot_prepare
3. Create an inbox of type Channel::Api.
4. Send a payload to create a conversation, for example:
`{
  "contact_id": 19204,
  "inbox_id": 29,
  "message": { "content": "ertywertywert" },
  "assignee_id": "1",
  "account_id": "3",
  "conversation": {
    "inbox_id": 29,
    "assignee_id": "1",
    "contact_id": 19204
  }
}`

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Docker (if applicable)

**docker version**
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.24
  GitCommit:        88bf19b2105c8b17560993bee28a01ddc2f97182
 runc:
  Version:          1.2.2
  GitCommit:        v1.2.2-0-g7cb3632
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**docker info**
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 28
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-48-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.25GiB
 Name: chatwoot-ubuntu
 ID: 535c1608-c009-41e5-8fe9-ed9f35eed64b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Docker Compose version v2.29.7

**Comment by Joeslinky** [comment]
Same error here!!

**Comment by sojan-official** [comment]
Please run the migrations post install and make sure your nodes are restarted as well.

**Comment by darkpixel** [comment]
No migrations to apply:

<img width="1589" height="104" alt="Image" src="https://github.com/user-attachments/assets/8d53ecd8-ceb5-4ccd-8272-cbaa71bb76c3" />

**Comment by darkpixel** [comment]
Downgrading to the 4.7.0 release fixes the issue.

**Comment by sojan-official** [comment]
@darkpixel  did you restart the containers after running the migrations ?

**Comment by darkpixel** [comment]
Yes.

**Comment by sojan-official** [comment]
@darkpixel  please check your database and make sure that ` assignee_agent_bot_id `  column is present in your database

**Comment by mahaddad** [comment]
After upgrading to 4.8.0 we are unable to create new conversations in the UI for WhatsApp inboxes.

<img width="546" height="85" alt="Image" src="https://github.com/user-attachments/assets/2629cf60-1fd4-4e1e-9052-d9d3a7c685df" />

Downgrading to 4.7.0 resolved it.

**Comment by TheEmanuelSampaio** [comment]
+1 - And yes @sojan-official the column `assignee_agent_bot_id` is present!

<img width="1423" height="559" alt="Image" src="https://github.com/user-attachments/assets/f141f383-5270-4f14-bcd0-e128acad80c1" />

```sql
CREATE TABLE "public"."conversations" ( 
  "id" SERIAL,
  "account_id" INTEGER NOT NULL,
  "inbox_id" INTEGER NOT NULL,
  "status" INTEGER NOT NULL DEFAULT 0 ,
  "assignee_id" INTEGER NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  "contact_id" BIGINT NULL,
  "display_id" INTEGER NOT NULL,
  "contact_last_seen_at" TIMESTAMP NULL,
  "agent_last_seen_at" TIMESTAMP NULL,
  "additional_attributes" JSONB NULL DEFAULT '{}'::jsonb ,
  "contact_inbox_id" BIGINT NULL,
  "uuid" UUID NOT NULL DEFAULT gen_random_uuid() ,
  "identifier" VARCHAR NULL,
  "last_activity_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  "team_id" BIGINT NULL,
  "campaign_id" BIGINT NULL,
  "snoozed_until" TIMESTAMP NULL,
  "custom_attributes" JSONB NULL DEFAULT '{}'::jsonb ,
  "assignee_last_seen_at" TIMESTAMP NULL,
  "first_reply_created_at" TIMESTAMP NULL,
  "priority" INTEGER NULL,
  "sla_policy_id" BIGINT NULL,
  "waiting_since" TIMESTAMP NULL,
  "cached_label_list" TEXT NULL,
  "assignee_agent_bot_id" BIGINT NULL,
  CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "index_conversations_on_first_reply_created_at" 
ON "public"."conversations" (
  "first_reply_created_at" ASC
);
CREATE INDEX "index_conversations_on_contact_id" 
ON "public"."conversations" (
  "contact_id" ASC
);
CREATE INDEX "index_conversations_on_priority" 
ON "public"."conversations" (
  "priority" ASC
);
CREATE INDEX "index_conversations_on_campaign_id" 
ON "public"."conversations" (
  "campaign_id" ASC
);
CREATE INDEX "index_conversations_on_assignee_id_and_account_id" 
ON "public"."conversations" (
  "assignee_id" ASC,
  "account_id" ASC
);
CREATE UNIQUE INDEX "index_conversations_on_account_id_and_display_id" 
ON "public"."conversations" (
  "account_id" ASC,
  "display_id" ASC
);
CREATE INDEX "index_conversations_on_account_id" 
ON "public"."conversations" (
  "account_id" ASC
);
CREATE INDEX "index_conversations_on_status_and_account_id" 
ON "public"."conversations" (
  "status" ASC,
  "account_id" ASC
);
CREATE INDEX "index_conversations_on_status_and_priority" 
ON "public"."conversations" (
  "status" ASC,
  "priority" ASC
);
CREATE INDEX "index_conversations_on_team_id" 
ON "public"."conversations" (
  "team_id" ASC
);
CREATE UNIQUE INDEX "index_conversations_on_uuid" 
ON "public"."conversations" (
  "uuid" ASC
);
CREATE INDEX "index_conversations_on_waiting_since" 
ON "public"."conversations" (
  "waiting_since" ASC
);
CREATE INDEX "index_conversations_on_identifier_and_account_id" 
ON "public"."conversations" (
  "identifier" ASC,
  "account_id" ASC
);
CREATE INDEX "index_conversations_on_contact_inbox_id" 
ON "public"."conversations" (
  "contact_inbox_id" ASC
);
CREATE INDEX "conv_acid_inbid_stat_asgnid_idx" 
ON "public"."conversations" (
  "account_id" ASC,
  "inbox_id" ASC,
  "status" ASC,
  "assignee_id" ASC
);
CREATE INDEX "index_conversations_on_inbox_id" 
ON "public"."conversations" (
  "inbox_id" ASC
);
CREATE INDEX "index_conversations_on_id_and_account_id" 
ON "public"."conversations" (
  "account_id" ASC,
  "id" ASC
);
```

**Comment by mahaddad** [comment]
Hi team - any update on this? We are unable to upgrade to 4.8.0 due to this error.

**Comment by jegade** [comment]
Restarting after migration solved the problem for me. I have a docker setup. Until now,  restarting after migration was never consciously necessary.

**Comment by sojan-official** [comment]
@jegade restarting the containers is always needed if there are any data migrations.

**Comment by sojan-official** [comment]
@mahaddad  please confirm if you have the column in your table and your server was restarted after migrations.

**Comment by sojan-official** [comment]
@TheEmanuelSampaio  did you restart the instances ?

**Comment by SantiSite** [comment]
I had the same problem. When running migrations, you must restart the server. If you are using Docker, run `docker compose down` again, then `docker compose up -d`, and you're done. @sojan-official thank you ❤️

**Comment by pinkypool** [comment]
> I had the same problem. When running migrations, you must restart the server. If you are using Docker, run `docker compose down` again, then `docker compose up -d`, and you're done. [@sojan-official](https://github.com/sojan-official) thank you ❤️

Tried: 
docker-compose down
docker-compose pull
docker-compose run --rm chatwoot bundle exec rails db:migrate
docker-compose up -d

Got:
Bundle complete! 142 Gemfile dependencies, 281 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `/gems`
1 installed gem you directly depend on is looking for funding.

Still have that issue, so any update on this? Really need that bulk contact  actions :D

**Comment by sojan-official** [comment]
@pinkypool  please confirm if the column name exists in your database.

**Comment by mahaddad** [comment]
> [@mahaddad](https://github.com/mahaddad) please confirm if you have the column in your table and your server was restarted after migrations.

@sojan-official it is working after we restarted. thanks!

**Comment by sojan-official** [comment]
Thanks for confirming that restarting the server after migrations resolved the issue. I'll close this ticket now, but please feel free to reopen or open a new issue if you run into any further problems.
