### ISSUE TITLE
Messages wont show up in version 3.4.0

### ISSUE THREAD

**Issue by ryonwhyte** [chatwoot/chatwoot#8608]
### Describe the bug

I installed chatwoot on Elestio a few weeks ago. It worked fine on version 3.3.1 and the vesrsion before that. Last night it was auto updated to version 3.4.0 and messages stopped showing up. It was just be stuck in a loading state. When new messages arrived a notification appeared in the notification pane but the message itself would not show up in a conversation (no conversation showed up) and as such I cannot respond. I downgraded to version 3.3.1 and everything is working fine again. The messages sent while on version 3.4.0 showed up as well. 

I am on Elestio.  Server type: MEDIUM-2C-4G (2 VCPU s - 4 GB RAM - 40 GB storage) Provider: hetzner. 
Ubuntu .22.04.2

There was no error in the logs. I will try to upgrade to 3.4.0 again in a few days and see what happens then. In c ase anyone else has this issue maybe they can drop here as well. 

### To Reproduce

Upgrade to version 3.4.0 on Ubuntu 22

### Expected behavior

Conversations should load on left panel and user should be able to open each conversation and respond to messages.

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 22.04.2

### Browser and version

Firefox and chrome latest

**Comment by prathapbelli** [comment]
we are also facing same issue, conversations are stuck loading, conversation apis are failing with 500 internal error after upgrade to 3.4.0
GET "/api/v1/accounts/1/conversations?status=open&assignee_type=unassigned&page=1&sort_by=last_activity_at_desc"

Completed 500 Internal Server Error
ActionView::Template::Error (undefined local variable or method `cached_label_list')

**Comment by arthurrferroni** [comment]
Execute the database migration and database prepare and restart the services

**Comment by prathapbelli** [comment]
> Execute the database migration and database prepare and restart the services

This document related migration is not much helpful, its has example migrate to managed database service.
we have existed database for chatwoot in our postgres service, we are able to tale pg_dump backup file what next?do we need to restore to same database or new database, what makes the difference.
https://www.chatwoot.com/docs/self-hosted/runbooks/migrate-chatwoot-database

**Comment by arthurrferroni** [comment]
RAILS_ENV=production POSTGRES_STATEMENT_TIMEOUT=600s bundle exec rake db:migrate
  RAILS_ENV=production POSTGRES_STATEMENT_TIMEOUT=600s bundle exec rake db:chatwoot_prepare

**Comment by ryonwhyte** [comment]
In case anyonw want to know. I ran these commands to fix my installation and 3.4.0 now works great.
```
cd /opt/app; docker-compose up -d;
docker-compose run --rm rails bundle exec rails db:migrate
docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
```

**Comment by arthurrferroni** [comment]
That's the same commands, but this for docker, the v3.4.0 has table's changes, so it's needs to be migrated/changed

**Comment by prathapbelli** [comment]
we have deployed using kubernetes and we have our own postgres service. any idea how to migrate using kubernetes.

**Comment by prathapbelli** [comment]
If you are using the official helm charts, helm upgrade will upgrade the application as well as run the pending db migrations.
To manually, run any pending migrations
ssh into any web pod
run
# Migrate the database schema
RAILS_ENV=production bundle exec rails db:chatwoot_prepare

**Comment by pranavrajs** [comment]
Anyone seeing similar issues in the future, this is mostly happening because you have a missing database migration. Please run the migrations and restart the services.
