### ISSUE TITLE
Disappearing Inboxes (after v3.0 upgrade)

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#7744]
### Describe the bug

After upgrading to v3 and logging in, my inboxes have disappeard:

<img width="1191" alt="image" src="https://github.com/chatwoot/chatwoot/assets/1176036/cbb51903-4c7b-4fc0-bd1f-2470b7a10492">

The URL after logging in reads `chatwoot.domain.tld/app/accounts/1/dashboard`. Now, when I clear the path out of the URL, so it reads `chatwoot.domain.tld`, and I press enter, everything appears to be in perfect working order:

<img width="1280" alt="image" src="https://github.com/chatwoot/chatwoot/assets/1176036/5bb4b047-57b5-4930-888c-544594c00783">

At this stage everything seems to be working fine – until after reloading the app manually, when the inboxes will be gone again.

### To Reproduce

I really do not know. I upgraded to v3, ran into issues due to node 18, installed 16, recompiled – and this is where I ended up.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

MacOS

### Browser and version

Current Chrome

### Additional context

Hosted on Hetzner

**Comment by vishnu-narayanan** [comment]
@jochenstu Which version of Chatwoot were you upgrading from? Also, your OS version?

**Comment by jochenstu** [comment]
Version: 2.18.0
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"

I have used and always upgraded this instance for about 12 month now using cwctl.

**Comment by vishnu-narayanan** [comment]
@jochenstu Thank you for letting us know. Just wanted to check whether you are upgrading from a very old version.

SInce the inboxes show up, migrations/upgrade seems to have worked. Could you try a different browser or incognito window? Any error logs on browser console?

**Comment by jochenstu** [comment]
Sure! After clearing the site cookies the issue is gone. Thanks for the pointer. I don't know what to make off that. Should probably better be avoided, but probably not worth investigating further.

**Comment by JustinBack** [comment]
Got the same issue, clearing cookies does not fix the bug.

Though I get the following errors in the rails console:

```
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] ActionView::Template::Error (undefined method `business_name' for #<Inb
ox id: 3, channel_id: 2, account_id: 1, name: "`******", created_at: "2023-07-31 21:52:03.511102000 +0000"
, updated_at: "2023-08-01 11:31:02.270205000 +0000", channel_type: "Channel::Email", enable_auto_assignment: true, greeting_
enabled: true, greeting_message: "Hallo {{contact.name}},\r\n\r\nVielen Dank für Ihre Na...", email_address: nil, working_ho
urs_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: true, allo
w_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, portal_id: 1, sender_name_t
ype: nil>):
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     17: json.allow_messages_after_resolved resource.allow_messages_afte
r_resolved
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     18: json.lock_to_single_conversation resource.lock_to_single_conver
sation
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     19: json.sender_name_type resource.sender_name_type
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     20: json.business_name resource.business_name
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     21: 
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     22: if resource.portal.present?
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     23:   json.help_center do
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]   
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/models/_inbox.json.jbuilder:20
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/accounts/inboxes/index.json.jbuilder:3
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/accounts/inboxes/index.json.jbuilder:2
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/accounts/inboxes/index.json.jbuilder:1
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_ac
count_locale'
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/request_exception_handler.rb:11:in `handle_wit
h_exception'
rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
```


```

rails_1     | F, [2023-08-17T20:27:08.275793 #1] FATAL -- : [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]   
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] ActionView::Template::Error (undefined method `waiting_since' for #<Con
versation id: 27, account_id: 1, inbox_id: 1, status: "open", assignee_id: 1, created_at: "2023-08-11 17:45:41.678476000 +00
00", updated_at: "2023-08-11 17:45:47.078781000 +0000", contact_id: 11, display_id: 27, contact_last_seen_at: nil, agent_las
t_seen_at: "2023-08-12 16:10:39.259802000 +0000", additional_attributes: {"mail_subject"=>"Buchhaltung"}, contact_inbox_id: 
16, uuid: "f7f6ee72-3e6e-40c2-a70a-89a076c6d16b", identifier: nil, last_activity_at: "2023-08-11 17:45:41.701298000 +0000", 
team_id: nil, campaign_id: nil, snoozed_until: nil, custom_attributes: {}, assignee_last_seen_at: "2023-08-12 16:10:39.25980
2000 +0000", first_reply_created_at: "2023-08-11 17:45:41.701298000 +0000", priority: nil, label_list: nil>):
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     46: json.last_non_activity_message conversation.messages.where(acco
unt_id: conversation.account_id).non_activity_messages.first.try(:push_event_data)
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     47: json.last_activity_at conversation.last_activity_at.to_i
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     48: json.priority conversation.priority
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     49: json.waiting_since conversation.waiting_since.to_i.to_i
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]   
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:49
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:10
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:9
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:8
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:1
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_ac
count_locale'
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/request_exception_handler.rb:11:in `handle_wit
h_exception'
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
rails_1     | I, [2023-08-17T20:27:08.276027 #1]  INFO -- : source=rack-timeout id=5b45fcf6-5518-4d3f-8f4e-a46e21031f0e time
out=15000ms service=139ms state=completed
```

**Comment by ZiekBaboon** [comment]
Same problem here.

From 2.18 to 3.0.0

updated to node 16
ubuntu 20

**Comment by ZiekBaboon** [comment]
Fixed after upgrading Ruby to 3.2.2, i was using 3.1

**Comment by sojan-official** [comment]
> Got the same issue, clearing cookies does not fix the bug.
> 
> Though I get the following errors in the rails console:
> 
> ```
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] ActionView::Template::Error (undefined method `business_name' for #<Inb
> ox id: 3, channel_id: 2, account_id: 1, name: "`******", created_at: "2023-07-31 21:52:03.511102000 +0000"
> , updated_at: "2023-08-01 11:31:02.270205000 +0000", channel_type: "Channel::Email", enable_auto_assignment: true, greeting_
> enabled: true, greeting_message: "Hallo {{contact.name}},\r\n\r\nVielen Dank für Ihre Na...", email_address: nil, working_ho
> urs_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: true, allo
> w_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, portal_id: 1, sender_name_t
> ype: nil>):
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     17: json.allow_messages_after_resolved resource.allow_messages_afte
> r_resolved
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     18: json.lock_to_single_conversation resource.lock_to_single_conver
> sation
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     19: json.sender_name_type resource.sender_name_type
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     20: json.business_name resource.business_name
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     21: 
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     22: if resource.portal.present?
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]     23:   json.help_center do
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013]   
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/models/_inbox.json.jbuilder:20
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/accounts/inboxes/index.json.jbuilder:3
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/accounts/inboxes/index.json.jbuilder:2
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/views/api/v1/accounts/inboxes/index.json.jbuilder:1
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_ac
> count_locale'
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/request_exception_handler.rb:11:in `handle_wit
> h_exception'
> rails_1     | [77cd69b8-78c0-4683-a067-9fff18abc013] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
> ```
> 
> ```
> 
> rails_1     | F, [2023-08-17T20:27:08.275793 #1] FATAL -- : [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]   
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] ActionView::Template::Error (undefined method `waiting_since' for #<Con
> versation id: 27, account_id: 1, inbox_id: 1, status: "open", assignee_id: 1, created_at: "2023-08-11 17:45:41.678476000 +00
> 00", updated_at: "2023-08-11 17:45:47.078781000 +0000", contact_id: 11, display_id: 27, contact_last_seen_at: nil, agent_las
> t_seen_at: "2023-08-12 16:10:39.259802000 +0000", additional_attributes: {"mail_subject"=>"Buchhaltung"}, contact_inbox_id: 
> 16, uuid: "f7f6ee72-3e6e-40c2-a70a-89a076c6d16b", identifier: nil, last_activity_at: "2023-08-11 17:45:41.701298000 +0000", 
> team_id: nil, campaign_id: nil, snoozed_until: nil, custom_attributes: {}, assignee_last_seen_at: "2023-08-12 16:10:39.25980
> 2000 +0000", first_reply_created_at: "2023-08-11 17:45:41.701298000 +0000", priority: nil, label_list: nil>):
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     46: json.last_non_activity_message conversation.messages.where(acco
> unt_id: conversation.account_id).non_activity_messages.first.try(:push_event_data)
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     47: json.last_activity_at conversation.last_activity_at.to_i
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     48: json.priority conversation.priority
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]     49: json.waiting_since conversation.waiting_since.to_i.to_i
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e]   
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:49
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:10
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:9
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:8
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/views/api/v1/accounts/conversations/index.json.jbuilder:1
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_ac
> count_locale'
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/request_exception_handler.rb:11:in `handle_wit
> h_exception'
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
> rails_1     | [5b45fcf6-5518-4d3f-8f4e-a46e21031f0e] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
> rails_1     | I, [2023-08-17T20:27:08.276027 #1]  INFO -- : source=rack-timeout id=5b45fcf6-5518-4d3f-8f4e-a46e21031f0e time
> out=15000ms service=139ms state=completed
> ```

This look like a case of migrations not being run.. 

also did you restart the services after running the migrations ?

**Comment by JustinBack** [comment]
Yeah I ran migrations and re-created containers

**Comment by sojan-official** [comment]
@JustinBack  could you login to the super admin and clear the frontend cache for this account. the option will be available in accounts edit page.

**Comment by grupale** [comment]
Hi @sojan-official I'm having the same issue after restoring a production database into a fresh updated instalation. After restoring I ran a manual update process an this errors ocurrs during migrations

![image](https://github.com/chatwoot/chatwoot/assets/10934794/6952b4d9-e5da-4e78-bbd5-3fbf7c50189c)
![image](https://github.com/chatwoot/chatwoot/assets/10934794/2a7a445b-7fb6-42c9-bcb7-f4ccacc43c11)
![image](https://github.com/chatwoot/chatwoot/assets/10934794/00a80b34-1f6b-4c9d-b781-a7d31ee87d48)


I'm upgrading from a restored database backup which ran v2.14

**Comment by grupale** [comment]
> Hi @sojan-official I'm having the same issue after restoring a production database into a fresh updated instalation. After restoring I ran a manual update process an this errors ocurrs during migrations
> 
> ![image](https://user-images.githubusercontent.com/10934794/265294748-6952b4d9-e5da-4e78-bbd5-3fbf7c50189c.png) ![image](https://user-images.githubusercontent.com/10934794/265294772-2a7a445b-7fb6-42c9-bcb7-f4ccacc43c11.png) ![image](https://user-images.githubusercontent.com/10934794/265294857-00a80b34-1f6b-4c9d-b781-a7d31ee87d48.png)
> 
> I'm upgrading from a restored database backup which ran v2.14. What sould I check or fix to run correctly the migrations? Thanks

Hi @sojan-official I've manage to solve this issue by deleting the index mentioned in the migration error. After deleting I ran again the update process and inboxes are working properly

**Comment by vishnu-narayanan** [comment]
@danielthedifficult Apologies for that 😅

For docker deployment method, one is expected to run the migrations after updating the image.

> Finally you may need to update the database: docker compose run --rm rails bundle exec rails db:chatwoot_prepare 
ref #1: https://www.chatwoot.com/docs/self-hosted/deployment/docker#upgrading
ref #2: https://www.chatwoot.com/docs/self-hosted/deployment/upgrade#docker

**Comment by danielthedifficult** [comment]
Okay. So it's something I add in my own upgrade and maintenance scripts, and not in the inherent upgrade process you create for a release. Ok!

**Comment by vishnu-narayanan** [comment]
@danielthedifficult Yes, for Linux/helm installations we handle the migration in the upgrade process. 

For docker, you will have to run it after every upgrade. And the migrations are idempotent. So no issues if you run it multiple times.

**Comment by danielthedifficult** [comment]
@vishnu-narayanan sorry to keep bugging you. I've read the links you've shared, and they explain perfectly "how" to do the upgrade, but i'm not 100% sur on when to implement it.

I have the following script that runs weekly to update the chatwoot service.

```
docker-compose down
docker-compose pull
docker-compose up -d
docker exec -it $(basename $(pwd))_rails_1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'
```

However the db migration is not getting executed properly. I think it is because the docker exec is running before the rails container is booted, but I'm not clear on how I should go about it. 

Any tips you have would be welcome.

**Comment by vishnu-narayanan** [comment]
@danielthedifficult Would adding a `sleep 30` after `docker-compose up -d` work?

**Comment by danielthedifficult** [comment]
Happy to do that, it's what I was thinking.

Do I need to reboot the stack again after a migration ?

**Comment by vishnu-narayanan** [comment]
> Do I need to reboot the stack again after a migration ?

Not needed

**Comment by lucianodltec** [comment]
> @JustinBack could you login to the super admin and clear the frontend cache for this account. the option will be available in accounts edit page.

I had this issue after deleting an inbox and this solution worked for me! Thanks @JustinBack

**Comment by gnwankpa** [comment]
> Sure! After clearing the site cookies the issue is gone. Thanks for the pointer. I don't know what to make off that. Should probably better be avoided, but probably not worth investigating further.

This worked for me
