### ISSUE TITLE
500 error when creating conversations via API in v4.8.0 (missing assignee_agent_bot_id)

### ISSUE THREAD

**Issue by joakimpm** [chatwoot/chatwoot#13100]
### Describe the bug

After upgrading from Chatwoot v4.7.0 to v4.8.0, creating conversations via the REST API fails with a 500 Internal Server Error.

The same integration and payload works correctly on v4.7.0 without any changes.

This impacts external integrations that programmatically create conversations.

### To Reproduce

Steps to reproduce
	1.	Upgrade Chatwoot to v4.8.0
	2.	Create or reuse an existing contact via the API
	3.	Create a conversation via:  POST /api/v1/accounts/:account_id/conversations
	4.     Use a minimal, valid payload (no assignee, no bot). Example below:
```
{
  "inbox_id": 35,
  "contact_id": 5831,
  "status": "open"
}
```

### Expected behavior

**Expected behavior**

The conversation should be created successfully as an unassigned conversation.

⸻

**Actual behavior**

The request fails with HTTP 500, and Chatwoot crashes internally.

**Rails error (v4.8.0)**
```
NameError: undefined local variable or method `assignee_agent_bot_id`
for an instance of Conversation
```

**Stack trace (trimmed)**
```
app/models/conversation.rb:188:in `assignee_type`
app/presenters/conversations/event_data_presenter.rb:34:in `push_meta`
app/listeners/action_cable_listener.rb:61:in `conversation_created`
app/controllers/api/v1/accounts/conversations_controller.rb:40:in `create`
```
The error occurs after the conversation is created, when Chatwoot builds event metadata.

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Docker (if applicable)

**docker version**
```
Client: Docker Engine - Community
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:41:48 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.11
  Git commit:       4c9b3b0
  Built:            Wed Jan 22 13:41:48 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**docker info**
```
Client: Docker Engine - Community
 Version:    27.5.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.20.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.4
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 42
 Server Version: 27.5.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-53-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.34GiB
 Name: xxx.xxxxx.com
 ID: 55dddc3c-459f-427b-8721-91c116aa3afe
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: xxx
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**docker compose version**
`Docker Compose version v2.32.4`

### Additional context

**Why this appears to be a Chatwoot bug**
	•	The API request does not include any assignee-related fields
	•	The integration does not reference assignee_agent_bot_id
	•	The crash happens in Chatwoot’s internal presenters/listeners
	•	The same flow works on v4.7.0
	•	Manually adding the missing DB column fixes the issue

This suggests a missing migration or a model change in v4.8.0 where
assignee_agent_bot_id is assumed to exist.
