### ISSUE TITLE
Instagram comment webhooks (field=comments) crash InstagramEventsJob: treated as Meta test event, TestEventService raises NoMethodError on nil sender

### ISSUE THREAD

**Issue by gmitre** [chatwoot/chatwoot#15494]
### Describe the bug

Real Instagram **comment** webhooks (e.g. comments on Reels) crash `Webhooks::InstagramEventsJob` with `NoMethodError: undefined method '[]' for nil`. Every comment on our connected Instagram account produces a failed job that retries and eventually lands in the Sidekiq dead set.

Root cause: comment events also arrive under `entry[:changes]` (with `field: "comments"`), and the job treats **any** entry with `changes` as a Meta *test* event:

```ruby
# app/jobs/webhooks/instagram_events_job.rb
def test_event?(entry)
  entry[:changes].present?
end
```

The extracted `value` of a comment event has `from` / `media` / `text` keys, not `sender` / `recipient`. `Instagram::TestEventService#test_webhook_event?` (introduced in #11244) then dereferences without a nil guard and raises:

```ruby
# app/services/instagram/test_event_service.rb
def test_webhook_event?
  @messaging[:sender][:id] == '12334' && @messaging[:recipient][:id] == '23245'
end
```

### To Reproduce

1. Connect an Instagram channel (Instagram login flow) and subscribe the app to the `comments` field (or simply have a user comment on a Reel of the connected account).
2. Meta delivers a webhook shaped like:

```json
{
  "entry": [
    {
      "id": "<ig-account-id>",
      "time": 1755300000,
      "changes": [
        {
          "field": "comments",
          "value": {
            "from": { "id": "<commenter-id>", "username": "someuser" },
            "media": { "id": "<media-id>", "media_product_type": "REELS" },
            "id": "<comment-id>",
            "parent_id": "<parent-id>",
            "text": "some comment text"
          }
        }
      ]
    }
  ],
  "object": "instagram"
}
```

3. `Webhooks::InstagramEventsJob` raises:

```
NoMethodError: undefined method '[]' for nil
  app/services/instagram/test_event_service.rb:17 in `test_webhook_event?`
  app/services/instagram/test_event_service.rb:9  in `perform`
  app/jobs/webhooks/instagram_events_job.rb:77    in `process_test_event`
  app/jobs/webhooks/instagram_events_job.rb:44    in `process_single_entry`
```

### Expected behavior

Comment webhooks that Chatwoot does not support should be ignored gracefully (job completes), instead of raising and retrying into the dead set.

A minimal fix is a nil-safe check, which also keeps the Meta test event working:

```ruby
def test_webhook_event?
  @messaging.dig(:sender, :id) == '12334' && @messaging.dig(:recipient, :id) == '23245'
end
```

Alternatively (or additionally), `test_event?` could require the test shape explicitly instead of matching any `changes` entry.

We are running this as a local monkey-patch initializer in production and it behaves as expected: the Meta test event path is unchanged and real comment events are ignored cleanly.

### Environment

- Chatwoot v4.16.2, self-hosted (Docker image `chatwoot/chatwoot:v4.16.2`), Kubernetes
- Instagram channel connected via Instagram login
- Ruby/Sidekiq as shipped in the image

**Comment by muhsin-k** [comment]
@gmitre Could you confirm whether you subscribed your Meta app to the Instagram comments webhook event?

**Comment by tiagofluz** [comment]
I am experiencing a very similar issue in Chatwoot v4.16.2-ce, also in `Webhooks::InstagramEventsJob`, but my failing event is `message_edit` instead of `comments`.

### Environment

- Chatwoot version: 4.16.2-ce
- Installation: self-hosted
- Deployment: Docker
- Channel: Instagram Direct
- Job backend: Sidekiq
- Ruby: 3.4.0
- Rails: 7.1.5.2
- Sidekiq: 7.3.1

### Failing event

The Instagram webhook event received by Chatwoot has this structure:

```text
object: instagram
event: message_edit
message_edit:
  mid: [redacted]
  num_edit: 0
```

The webhook endpoint receives the event and returns:

```text
HTTP 200 OK
```

However, the background job fails later in Sidekiq:

```text
WebhooksInstagramEventsJob
```

### Error

```text
NoMethodError undefined method for nil
```

The stack trace points to:

```text
app/jobs/webhooks/instagram_events_job.rb:88
WebhooksInstagramEventsJob#instagram_id
```

Relevant stack trace:

```text
NoMethodError undefined method for nil
app/jobs/webhooks/instagram_events_job.rb:88 in WebhooksInstagramEventsJob#instagram_id
app/jobs/webhooks/instagram_events_job.rb:55 in block in WebhooksInstagramEventsJob#process_messages
app/jobs/webhooks/instagram_events_job.rb:52 in Array#each
app/jobs/webhooks/instagram_events_job.rb:52 in WebhooksInstagramEventsJob#process_messages
app/jobs/webhooks/instagram_events_job.rb:48 in WebhooksInstagramEventsJob#process_single_entry
app/jobs/webhooks/instagram_events_job.rb:36 in block in WebhooksInstagramEventsJob#process_entries
app/jobs/webhooks/instagram_events_job.rb:35 in Array#each
app/jobs/webhooks/instagram_events_job.rb:35 in WebhooksInstagramEventsJob#process_entries
app/jobs/webhooks/instagram_events_job.rb:24 in block in WebhooksInstagramEventsJob#perform
```

Normal Instagram message events work correctly. The failure appears to be specific to the `message_edit` event path.

The Sidekiq job is retried repeatedly and eventually moved to the dead queue.

Example job IDs:

```text
70a0dae6-013a-4c82-9bd0-501c31d57f73
8448cfb3-70f1-4217-ab4d-f6f597e7ad9e
```

### Expected behavior

Unsupported or malformed Instagram events such as `message_edit` should be ignored gracefully, or processed without raising an exception.

The job should not enter a repeated retry cycle and should not end up in the Sidekiq dead queue.

This seems related to the same general issue described here, where Instagram webhook payloads with a different structure are incorrectly processed by `Webhooks::InstagramEventsJob`.

A nil-safe payload validation or explicit event-type check may solve both cases.

Error performing WebhooksInstagramEventsJob
NoMethodError undefined method for nil
app/jobs/webhooks/instagram_events_job.rb:88
WebhooksInstagramEventsJob#instagram_id

The Instagram integration with Chatwoot Community was successfully configured. The webhook was verified by Meta and returned 200 OK. Instagram events were successfully received and processed through the /webhooks/instagram endpoint. Messages were identified by Chatwoot as ChannelInstagram, converted into conversations in the Instagram inbox, and correctly forwarded to the n8n automation webhook.
