### ISSUE TITLE
Merging a contact orphans its `calls`, causing 500 on the account Calls dashboard (#14954)

### ISSUE THREAD

**Issue by lxndr-rl** [chatwoot/chatwoot#15087]
### Describe the bug

When merging two contacts (`ContactMergeAction`), the `calls` records belonging to the mergee contact are **not** reassigned to the base contact before the mergee contact is destroyed. The `Call` model has a `not null` `contact_id` column with `belongs_to :contact` (no `optional: true`), so once the mergee contact is deleted, any pre-existing `Call` row still points to a `contact_id` that no longer exists — `call.contact` returns `nil` for that orphaned record.

This causes a 500 error on `GET /api/v1/accounts/:account_id/calls` (the account calls dashboard index endpoint, added in #14780) as soon as pagination reaches a page containing one of these orphaned calls, because `app/views/api/v1/models/_call.json.jbuilder` calls `contact.id` unconditionally:
```ruby
ActionView::Template::Error (undefined method 'id' for nil):
34: contact = call.contact
35: json.contact do
36:   json.id contact.id
```

The bug itself predates #14954, but #14954 ("introduce voice call dashboard") is what surfaces it in practice: it adds the dashboard-wide Calls view (`CallsIndex.vue` / `stores/callHistory.js`) that actually paginates through *all* calls in the account, so any orphaned `Call` left behind by a previous contact merge now gets rendered and blows up the page with a 500 instead of silently never being queried.

Every other association touched by a contact merge is migrated correctly (`Conversation`, `Message`, `ContactInbox`, `Note`), but `Call` was added later (unified Call model / WhatsApp Cloud Calling, #14026, #14315, #14346, #14780, #14954) and `ContactMergeAction` was never updated to account for it.

There is a **second, related bug on the frontend**: once the backend is patched to return `contact: null` instead of 500ing, `CallListItem.vue` crashes instead, because it also assumes `call.contact` always exists:
```
callHistory.js:23 TypeError: Cannot read properties of null (reading 'avatar')
    at Proxy.<anonymous> (CallListItem.vue:74:3)
    ...
    at fetchCalls @ callHistory.js:23
```
`CallListItem.vue` reads `call.contact.name`, `call.contact.phoneNumber` (line 29) and `call.contact.avatar` (lines 81 and 152) with no null check. So a fully correct fix needs both the backend reassignment/guard and a frontend guard — otherwise fixing one side just moves the crash to the other.

### To Reproduce

1. Open the account-wide Calls dashboard introduced in #14954 (`/app/accounts/:id/calls` or similar), with an account that has enough call history to paginate (in this case: 240 calls across 10 pages, 25 per page).
2. Browse normally through the list — the first pages render fine.
3. Navigate to the **last page** (`GET /api/v1/accounts/:account_id/calls?page=10`).
4. If any `Call` record in that page belongs to a contact that was later deleted via a contact merge (`ContactMergeAction`), the request fails with a 500 instead of rendering the page.
5. Server log:
```
Started GET "/api/v1/accounts/1/calls?page=10" ...
Completed 500 Internal Server Error ...
ActionView::Template::Error (undefined method 'id' for nil):
34: contact = call.contact
35: json.contact do
36:   json.id contact.id
```

Note: the failure is **not** triggered at the moment of merging two contacts — merging succeeds silently. The 500 only appears later, whenever the Calls dashboard happens to paginate to a page containing one of the now-orphaned `Call` rows (in this case, page 10 of 10). This makes the bug hard to notice right after a merge and only surfaces once someone browses deep enough into call history.

Minimal reproduction to confirm root cause without needing 240 real calls:
1. Create `contact_a` (base) and `contact_b` (mergee) with a `Call` where `contact_id = contact_b.id`.
2. Merge them: `ContactMergeAction.new(account:, base_contact: contact_a, mergee_contact: contact_b).perform`.
3. `contact_b` is destroyed; the call's `contact_id` now points nowhere.
4. `GET /api/v1/accounts/:account_id/calls` — as soon as pagination reaches that call, same 500.
5. If the backend `_call.json.jbuilder` nil-check is applied on its own (without also patching the frontend), the 500 goes away but the dashboard tab now hard-crashes on `call.contact.avatar` instead (see console trace above), because `CallListItem.vue` never expected a `null` contact either.

### Expected behavior

Merging a contact should reassign its `calls` to the base contact, the same way it already does for conversations, messages, notes, and contact inboxes — so no `Call` is left pointing at a deleted contact, and the Calls dashboard from #14954 never hits this. As defense in depth:
- `_call.json.jbuilder` should not blow up if `call.contact` is unexpectedly `nil` (e.g. for calls that already got orphaned before the fix, or from any other code path that could remove a contact without cleaning up its calls).
- `CallListItem.vue` should not assume `call.contact` is present either — it should fall back to something like "Deleted contact" instead of crashing the whole list render.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 24.04.3 LTS

### Browser and version

Brave 1.92.141 (Build oficial) (64 bits) Chromium: 150.0.7871.128

### Docker (if applicable)

```
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:23 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:23 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.2.1
  GitCommit:        dea7da592f5d1d2b7755e3a161be07f43fad8f75
 runc:
  Version:          1.3.4
  GitCommit:        v1.3.4-0-gd6d73eb8
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.30.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v5.0.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 13
  Paused: 0
  Stopped: 4
 Images: 19
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: REDACTED_NODE_ID
  Is Manager: true
  ClusterID: REDACTED_CLUSTER_ID
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: REDACTED_SERVER_IP
  Manager Addresses:
   REDACTED_SERVER_IP:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: dea7da592f5d1d2b7755e3a161be07f43fad8f75
 runc version: v1.3.4-0-gd6d73eb8
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-134-generic
 Operating System: Ubuntu 24.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.755GiB
 Name: REDACTED_HOSTNAME
 ID: REDACTED_DOCKER_ID
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: REDACTED_USERNAME
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by AdityaAudi** [comment]
Hi Team, happy to take this one, could you assign it to me?

I found the cause. `ContactMergeAction` moves conversations, messages, contact_inboxes and notes over to the base contact but never reassigns `calls`, so once the mergee is destroyed its calls are left pointing at a contact that no
longer exists. `Call#contact` is a required association, so the calls index from #14780 blows up in `_call.json.jbuilder` on `contact.id` the moment pagination hits one of those orphaned rows.

The bit I want to get right before opening a PR is the enterprise split: `Call`, its controller and the jbuilder all live under `enterprise/`, but `ContactMergeAction` is OSS and isn't set up with `prepend_mod_with` today. So rather than reaching for the `Call` constant from OSS, I'd add a `merge_calls` step via an enterprise override (mirroring `merge_conversations`), plus a nil guard in the jbuilder to cover calls that are already orphaned from before the fix, and a matching guard in `CallListItem.vue` so a missing contact renders as "Deleted contact" instead of crashing the list. Tests would go under `spec/enterprise`.

Does that line up with how you'd want the OSS/enterprise boundary handled here, or is there an existing override pattern you'd rather I follow?
