### ISSUE TITLE
[v4.10.1] Telegram attachments fail with "undefined method '[]' for nil" in SendReplyJob after update to v4.10.1

### ISSUE THREAD

**Issue by publicsmoke** [chatwoot/chatwoot#13415]
### Describe the bug

After migrating our self-hosted instance (Docker) to a new server, outgoing file attachments to Telegram stopped working. The job fails in Sidekiq with `NoMethodError`.

Everything else works fine:
- Incoming Telegram messages and files arrive correctly.
- Text-only replies to Telegram work.
- The attached files are saved correctly in local storage and I can download them via the public URL generated by Chatwoot.
- `ACTIVE_STORAGE_SERVICE=local` is set and working.

**The Error:**
In Sidekiq > Dead Jobs, I see `SendReplyJob` failing with:
`NoMethodError: undefined method '[]' for nil`

**Stack Trace:**
app/models/channel/telegram.rb:63:in `process_error'
app/services/telegram/send_attachments_service.rb:129:in `handle_response'
app/services/telegram/send_attachments_service.rb:84:in `block in send_individual_attachments'
app/services/telegram/send_attachments_service.rb:82:in `map'
app/services/telegram/send_attachments_service.rb:43:in `send_attachments'
app/jobs/send_reply_job.rb:27:in `perform'

**Debug Info:**
I checked the failing message in Rails console:
- File type: `text/plain` (also happens with images)
- File size: 608 bytes (small)
- `file_url`: Generates a valid public URL that is accessible from outside.
- Network: `Net::HTTP.get_response(URI("https://api.telegram.org"))` from inside the container returns 302/200 OK.

### To Reproduce

1. Setup Chatwoot v4.10.1 (Docker) with Telegram channel.
2. Send a file (e.g. .txt or image) from Chatwoot dashboard to the Telegram contact.
3. Observe that the job fails in Sidekiq with `NoMethodError`.

### Expected behavior

Outgoing messages with file attachments from Chatwoot to Telegram should be delivered successfully.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Docker (if applicable)

docker version: 24.0.5 (or similar latest)
docker-compose version: v2.20.2

**Comment by publicsmoke** [comment]
I think was fixed in 4.11.1 or maybe in  4.11.0
